In [2]:
import pandas as pd
df = pd.read_csv("tweets.csv")
df

,token,date,reply_count,like_count,retweet_count,quote_count,text,sentiment_label,sentiment_score
0,bitcoin,2022-01-01 00:00:00.000,20,207,31,3,Most people underestimate the impact #Bitcoin ...,Neutral,0.717482
1,bitcoin,2022-01-01 00:00:00.000,232,3405,286,27,#Bitcoin has started a new yearly candle https...,Neutral,0.810814
2,bitcoin,2022-01-01 00:00:00.000,2,861,12,0,@DESTROYBINARY did people forget that the amog...,Neutral,0.606978
3,bitcoin,2022-01-01 00:00:00.000,18,306,30,9,"In 2017, miners attempted to assert control ov...",Negative,0.510956
4,bitcoin,2022-01-01 00:00:00.000,35,721,35,1,Yearly Close \nMonthly Close\nDaily Close\n\nh...,Positive,0.988296
...,...,...,...,...,...,...,...,...,...
76792,bitcoin,2023-06-22 00:00:00.000,8,204,35,2,IMF says while a few countries have banned #Bi...,Negative,0.615765
76793,bitcoin,2023-06-22 00:00:00.000,8,298,17,4,"Fear, Greed &amp; Bitcoin | #SheCrypto https:/...",Neutral,0.687251
76794,bitcoin,2023-06-22 00:00:00.000,17,86,17,0,I know I may be unpopular for saying this but ...,Neutral,0.532809
76795,bitcoin,2023-06-22 00:00:00.000,193,3048,771,42,#Bitcoin now has the support of presidential c...,Positive,0.935171
76796,bitcoin,2023-06-22 00:00:00.000,53,43524,46438,1,All unclaimed tokens will be burned by 4:00PM ...,Neutral,0.758979

In [4]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()
df['fscore'] = df['text'].apply(lambda review: sid.polarity_scores(review)['compound'])

[nltk_data] Downloading package vader_lexicon to C:\Users\Hp-
[nltk_data]     admin\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [5]:
result = df.groupby('date')['fscore'].mean()

In [6]:
result

date
2022-01-01 00:00:00.000    0.239093
2022-01-02 00:00:00.000    0.163560
2022-01-03 00:00:00.000    0.193299
2022-01-04 00:00:00.000    0.154669
2022-01-05 00:00:00.000    0.059539
                             ...
2023-06-18 00:00:00.000    0.206328
2023-06-19 00:00:00.000    0.120098
2023-06-20 00:00:00.000    0.090919
2023-06-21 00:00:00.000    0.219896
2023-06-22 00:00:00.000    0.158499
Name: fscore, Length: 538, dtype: float64

In [10]:
bitcoin_df = pd.read_csv("dataset.csv")

              Date     Price      Open      High       Low    Vol. Change %
0     Feb 09, 2024  47,545.4  45,293.3  47,710.2  45,254.2  86.85K    4.97%
1     Feb 08, 2024  45,293.3  44,346.2  45,579.2  44,336.4  66.38K    2.15%
2     Feb 07, 2024  44,339.8  43,088.4  44,367.9  42,783.5  48.57K    2.91%
3     Feb 06, 2024  43,087.7  42,697.6  43,375.5  42,566.8  33.32K    0.91%
4     Feb 05, 2024  42,697.2  42,581.4  43,532.2  42,272.5  39.26K    0.27%
...            ...       ...       ...       ...       ...     ...      ...
4950  Jul 22, 2010       0.1       0.1       0.1       0.1   2.16K    0.00%
4951  Jul 21, 2010       0.1       0.1       0.1       0.1   0.58K    0.00%
4952  Jul 20, 2010       0.1       0.1       0.1       0.1   0.26K    0.00%
4953  Jul 19, 2010       0.1       0.1       0.1       0.1   0.57K    0.00%
4954  Jul 18, 2010       0.1       0.0       0.1       0.1   0.08K    0.00%

[4955 rows x 7 columns]